### ISSUE TITLE
Problem with early exit

### ISSUE THREAD

**Issue by github4sanjay** [MighTguY/customized-symspell#10]
SpellHelper.earlyExit(suggestionItems, phrase, maxEditDistance);
Adding items inside this method seems to be wrong

**Comment by github4sanjay** [comment]
It gives two result when input is 
{
  "editDistance": 0,
  "input": "elephant",
  "verbosity": "TOP"
}

And it hard to understand the reason to add item with maxEditDistance + 1
suggestionItems.add(new CorrectionTuple(phrase, maxEditDistance + 1, 0));

**Comment by MighTguY** [comment]
Hi @github4sanjay, Thanks for noticing the same, will be fixing the same.

**Comment by MighTguY** [comment]
@github4sanjay , Issue has been fixed in 6.6.47

**Comment by github4sanjay** [comment]
But when word is too long, it will add one suggestion instead of sending empty list.

**Comment by MighTguY** [comment]
Now the settings have ignore unknown word flag, whose default value is false. This will Ignore the word in the resultset, if suggestions are empty
