### ISSUE TITLE
Factor should be configurable

### ISSUE THREAD

**Issue by github4sanjay** [MighTguY/customized-symspell#21]
private static Double getEdistance(double maxEditDistance, int length) {
    double factor = 0.3;
    double computedEd = Math.round(factor * length);
    if (Math.min(maxEditDistance, computedEd) == maxEditDistance) {
      return maxEditDistance;
    }
    return computedEd;
  }

This factor should be configurable in Spellchecksettings.

**Comment by MighTguY** [comment]
I have raised the pull request to set the editFactor in the Spellcheck settings,
the default value is 0.3

**Comment by MighTguY** [comment]
PR has been merged, It is now available in the latest version

**Comment by github4sanjay** [comment]
thanks
