### ISSUE TITLE
isTransposition

### ISSUE THREAD

**Issue by heymannheidelberger** [MighTguY/customized-symspell#43]
Hi, for e it looks like the method isTransposition is bugged:  

private boolean isTransposition(int i, int j, String a, String b) {
    return i > 2
        && j > 2
        && a.charAt(i - 2) == a.charAt(i - 1)
        && b.charAt(j - 2) == b.charAt(j - 1);
  }

The letters of the strings a and b are not compared with each other. You check whether a and b have consecutive characters being identical. Shouldn't it be the following?

private boolean isTransposition(int i, int j, String a, String b) {
    return i > 2
        && j > 2
        && a.charAt(i - 2) == b.charAt(j - 1)
        && b.charAt(j - 2) == a.charAt(i - 1);
  }

**Comment by MighTguY** [comment]
Thanks for pointing  it out, Checking on the same

**Comment by MighTguY** [comment]
@heymannheidelberger 
I have fixed the issue in the Class
