### ISSUE TITLE
Extra space is not trimmed in suggestions from lookupCompound()

### ISSUE THREAD

**Issue by aTan-aka-Xellos** [MighTguY/customized-symspell#49]
SymSpellCheck.class
lookupCompound()
Line 113
```      joinedTerm = joinedTerm.concat(si.getTerm()).concat(" ");````
results that the joinedTerm end with space.

For example, the next line that calculates editDistance trim() the joinedTerm, while it should trim() the stored result.

phrase: "ipd"
extected joinedTerm: "ipad"
actual joinedTerm: "ipad " 

Same for the multiword phase.  

![Screen Shot 2020-06-04 at 12 02 32](https://user-images.githubusercontent.com/7886823/83710482-d096cd00-a65b-11ea-8ed5-4206b1d5fe24.jpg)

**Comment by MighTguY** [comment]
This has been fixed in 
#pull50

Thanks for raising the same :)
