### ISSUE TITLE
Maven Repository

### ISSUE THREAD

**Issue by github4sanjay** [MighTguY/customized-symspell#8]
Could you please create maven repository so that we can use this as library?

**Comment by MighTguY** [comment]
Hi @github4sanjay, Sure will create the maven repo

**Comment by MighTguY** [comment]
Hi @github4sanjay, I have created the maven repository for the same, 
https://search.maven.org/search?q=io.github.mightguy

**Comment by github4sanjay** [comment]
thanks

**Comment by loretoparisi** [comment]
@MighTguY could you please details the `mvn` commands to build the project. Thank you.

**Comment by loretoparisi** [comment]
**[UPDATE]**

I was able to make it working with

```
$ mvn compile
$ mvn package
```

and the I got the jar with dependencies in `/target/.

Thank you.

**Comment by MighTguY** [comment]
I have fixed the same, Now mvn clean install will push to local .m2, and will not ask for gpg
